### ISSUE TITLE
Allow expression node to consider main input

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux#51]
This should work:         
```
expr: i + i_additional
eval_on = `ports`
```

But it currently doesn't.

I also wonder whether it should be:
```
expr: i + additional
eval_on = `ports`
```
i.e. whether it would be more elegant to supply the port suffix rather than the port name. After all, the suffix is what is used in yaml (e.g. when defining edges) and the expression is defined in the yaml.

**Comment by jonathanjfshaw** [comment]
Looks like you actually changed this recently deliberately:
https://github.com/timeflux/timeflux/commit/3100c4ebc0c4504fe11a6c7c4037a57cb3d5f885

**Comment by mesca** [comment]
Does that fix your issue?

**Comment by bertrandlalo** [comment]
Hi @jonathanjfshaw, 

Thank's for sharing your point 🙏. If I understand well, you want to (1) use the default port `i` in the expression and (2) change the expression definition by referring to a port by its suffix only. 
First would be an issue and second would be an improvement suggestion. 

- I think I don't really agree with the first, ie. allow using default port in expression. To me, the ports variables should remain **named ports**,  as it is more explicite. Furthermore, I think it makes the code more complicated, for few benefits. 
- I quite agree with the second, that the syntax with only suffix could be more intuitive. For exemple: 
```
    nodes: 
    - id: num 
      ...
    - id: den
      ... 
    - id: divide
      module: timeflux.nodes.expression
      class: Expression
      params:
        eval_on: ports
        expr: num/den   // instead of i_num/i_den
    edges:
    - source: num
      target: divide:num
    - source: den
      target: divide:den
```
But I'm thinking that this would also imply that the user couldn't use numbers as suffix then, otherwise it may be confusing with expressions such as `i_1 + 5*i_2`, or else... 
@mesca, what do you think? 

**PS:** What you suggest doing `if hasattr(self, "i"):` would not do what you expect since this assertion is always True even if the port is not plugged or not ready.

**Comment by jonathanjfshaw** [comment]
> To me, the ports variables should remain named ports, as it is more explicit.

Fair enough, I can see the validity in that way of thinking.

One question that brought me to think about this was that I created a filter node that I find very useful, and was planning to offer to you:

```
class ExpressionFilter(Expression):

    """Filter values using an expression

    See timeflux.nodes.expression.Expression.

    Use the dropna parameter to determine whether rows containing NANs should be dropped.
    """

    def __init__(self, **kwargs):
        self._drop_na = kwargs.pop("drop_na", False)
        super().__init__(**kwargs)

    def update(self):
        self.update_par()
        if self.o.data is not None:
            self.o.data = self.i.data.where(self.o.data)
        if self._drop_na:
            self.o.data = self.o.data.dropna()
```

Which I was using like this:
```
nodes:
    - id: my_gate
      module: my_package.nodes.expressionfilter
      class: ExpressionFilter
      params:
        expr: i < my_other_signal
        eval_on: ports
edges:
  - source: my_signal_needing_filtering
    target: my_gate
  - source: my_other_signal
    target: my_gate:my_other_signal
```


But I could easily change it so that it works like this
```
nodes:
    - id: my_gate
      module: my_package.nodes.expressionfilter
      class: ExpressionFilter
      params:
        target: my_signal_needing_filtering 
        expr: my_signal_needing_filtering < my_other_signal
        eval_on: ports
edges:
  - source:my_gate:my_signal_needing_filtering
    target: my_gate:my_signal_needing_filtering
  - source: my_other_signal
    target: my_gate:my_other_signal
```

It requires another parameter for ExpressionFilter, but that's not a big problem.
