### ISSUE TITLE
Apply node wrongly requires method parameter

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux#54]
AFAICS from the docs this should work:
```
    - id: my_apply
      module: timeflux.nodes.apply
      class: ApplyMethod
      params:
        func: abs
```
but it fails with `Node 'my_apply': __init__() missing 1 required positional argument: 'method'`, because the signature is 
```
    def __init__(self, method, apply_mode='universal',
                 axis=0, closed='right', func=None, **kwargs):
```

We should make `method` optional and raise an exception unless at least one of method and func are provided.
