### ISSUE TITLE
Use suffixes in expressions

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux#67]
In #51 our discussion diversified to include the possibility of using suffixes (instead of port names) in expressions.

For example:
```
nodes: 
    - id: num 
      ...
    - id: den
      ... 
    - id: divide
      module: timeflux.nodes.expression
      class: Expression
      params:
        eval_on: ports
        expr: num/den   // instead of i_num/i_den
    edges:
    - source: num
      target: divide:num
    - source: den
      target: divide:den
```

@bertrandlalo liked the idea, but added:
"But I'm thinking that this would also imply that the user couldn't use numbers as suffix then, otherwise it may be confusing with expressions such as i_1 + 5*i_2, or else..."
